# Kubernetes
alias k='kubectl'
alias kex='kubectl exec -i -t'
alias klo='kubectl logs -f'
alias kpf='kubectl port-forward'
alias kg='kubectl get'
alias kd='kubectl describe'
alias krm='kubectl delete'
alias klpo='kubectl get pod'
alias kgpo='kubectl get pod -o=yaml'
alias kldep='kubectl get deployment'
alias kgdep='kubectl get deployment -o=yaml'
alias klsvc='kubectl get service'
alias kgsvc='kubectl get service -o=yaml'
alias kling='kubectl get ingress'
alias kging='kubectl get ingress -o=yaml'
alias klcm='kubectl get configmap'
alias kgcm='kubectl get configmap -o=yaml'
alias klsec='kubectl get secret'
alias kgsec='kubectl get secret -o=yaml'
